<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<?php
		$auto = $this->getConfig('auto');
		$itemsDefault = $this->getConfig('itemsDefault');
		$itemsDesktop = $this->getConfig('itemsDesktop');
		$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
		$itemsTablet = $this->getConfig('itemsTablet');
		$itemsMobile = $this->getConfig('itemsMobile');
		$speed = $this->getConfig('speed');
		$next_back = $this->getConfig('next_back');
		$nav_ctrl = $this->getConfig('nav_ctrl');
	?>
	<div class="ma-featuredproductslider-container">
		<div class="container">
		<?php				
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="ma-featured-sldier-title"><h2><span><?php echo $this->getConfig('title')?></span></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> 
			<div class="ma-bestseller-slider">	
				<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>
			<div class="row">
				<ul class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<li class='featuredproductslider-item'>"; ?>
						<div class="item-inner">
							<?php
								$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
								$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();                 
								$now = date("Y-m-d H:m(worry)");
								// Get the Special Price
								$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
								// Get the Special Price FROM date
								$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
								// Get the Special Price TO date
								$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
								// Get Current date
								if(($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')) or ($newFromDate <= $now && $newToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label') )){
									if($newFromDate <= $now && $newToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label') ) {
										echo "<div class='label-pro-new'><h3>(new)</h3></div>";
										//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
									}
									if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')){
										echo "<div class='label-pro-sale'><h3>(sale)</h3></div>";
									} 
								}
							?>
						<div class="box-item">
							<div class="icon-item"></div>
							<div class="products clearfix">
								<div class="product">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									<span class="product-image">
								   <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270,347); ?>" width="270" height="347" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								  </span>
								  <span class="product-image image-rotator images-hover">
								   <?php 
								   $product = $_product;
								   if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
									//$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
									$image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize(270, 347);
								   } else {
									$image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(270, 347);
								   }
								   ?>
								   <img src="<?php echo $image ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 	'small_image'), null, true) ?>" />
								   </span>   
									</a>
								</div>
							</div>
							<?php if( $this->getConfig('show_price') ): ?>
								<div class="item-price">
								<div class="price-box">
									<?php
									$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
									$price = $_product->getPrice();
									$specialprice = $_product->getFinalPrice();
									if($price != $specialprice){
									if($price != ''){
									echo '<p class="old-price"><span class="price-label">';
									echo $this->__('Regular Price'). ': </span>';
									echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
									}
									if($specialprice != '')
									{
									echo '<p class="special-price">
									<span class="price-label">Special Price</span>
									<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
									</p> ';
									} 
									}else {
									echo '<div class="price-boxs">
									<span class="regular-price">
									<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
									</span>    
									</div>';    
									}
									?>
								</div>
								</div>
							<?php endif; ?>
							<div class="actions">
								<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') ){?>
									<ul class="add-to-links">
										<li>
										<?php if ($this->getConfig('addtocart')) { ?>
											<?php if($_product->isSaleable()): ?>
												<button type="button"  class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
											<?php else: ?>
												<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
											<?php endif; ?>
										<?php }?>
										</li>
										<?php if( $this->getConfig('addtowishlist')): ?>
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
												<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Wishlist') ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
											<?php endif; ?>
										<?php endif; ?>
				
										<?php if( $this->getConfig('addtocompare')): ?>
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
												<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Compare') ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
											<?php endif; ?>
										<?php endif; ?>
										<li>
											<a class="product-detail-link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->__('Details') ?>" rel="tooltip"><?php echo $this->__('Details') ?></a>
										</li>
									</ul>
								<?php }?>
							</div>
						</div>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
							<?php if($this->getConfig('review')): ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php endif; ?>
							<?php if( $this->getConfig('description')){?>
							<div class="ma-desc">
								<?php if(!$this->getConfig('maxlength')){?>
									<?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
								<?php } else {?>
									<?php echo nl2br($this->cut_string_featuredproductslider($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
								<?php }?>			                    
							</div>
						<?php }?>
							<?php $i++;?>					
						</div>
						<?php if($i %$rows == 0) echo "</li>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>                
				</ul>
			</div>
<script type="text/javascript">
	$jq(document).ready(function(){
	  $jq(".ma-featuredproductslider-container .owl").owlCarousel({
			autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
			items : <?php if($itemsDefault) echo $itemsDefault; else echo '6'; ?>,
			itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
			itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
			itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
			itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
			slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
			stopOnHover : true,
			pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
			scrollPerPage:true,
		});
	});
</script>
			
		<?php endif; ?>
		</div>
	</div> 
<?php } ?>


