<div class="ma-block-group">
	<div class="block-group">
	<div class="container">
		<div class="row">
			<div class=" col-md-8 col-sm-12 col-sms-12 col-smb-12">
				<?php  echo $this->getLayout()->createBlock('newproductslider/newproductslider')->setTemplate('magentothem/newproductslider/newproductslider.phtml')->toHtml(); ?>
			</div>
			<div class=" col-md-4 col-sm-12 col-sms-12 col-smb-12">
				<?php  echo $this->getLayout()->createBlock('blog/menu_sidebar')->setTemplate('magentothem_blog/blog_slide.phtml')->toHtml(); ?>
			</div>
		</div>
	</div>
		
	</div>
</div>
<div class="brand-slider">
	<div class="container">
		<div class="container-inner">
			<?php  echo $this->getLayout()->createBlock('brandslider/brandslider')->setTemplate('magentothem/brandslider/brandslider.phtml')->toHtml(); ?>
		</div>
	</div>
</div>
