<?php
$title = $this->getTitle();
$identify = $this->getIdentify();
$categoryIds = $this->getCatIds();
$categoryIds = explode(',', $categoryIds);
$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
if(!$productsOnRow) $productsOnRow = 3;
if ( !$this->getWidthThumbnail() ){
	$w_thumbnail = 135;
} else {
	$w_thumbnail = $this->getWidthThumbnail();
}
if( !$this->getHeightThumbnail() ){
	$h_thumbnail = 135;
 }
else {
	$h_thumbnail = $this->getHeightThumbnail();
}
?>

<div class="tab-container">
<?php 	echo '<h2>'.$title.'</h2>'; ?>
  <ul class="tabs tabs<?php echo '-'.$identify;?>"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model = Mage::getModel('catalog/category');
		$cateName = $cate_model->load($cate_id)->getName();
		
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>" ><?php  echo $cateName; ?></li>
	<?php }  $k++; } ?>
    </ul>

	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) { ?>
		 <div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
			<?php $_productCollection = $this->getProductCate($cate_id); ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $productsOnRow; ?>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
			<?php if ($i++%$_columnCount==0): ?>
			<ul class="products-grid">
			<?php endif ?>
				<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<div class="products clearfix">
						<div class="product">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
							<span class="product-image">
						   <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(69,87); ?>" width="69" height="87" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						  </span>
						  <span class="product-image image-rotator images-hover">
						   <?php 
						   $product = $_product;
						   if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
							//$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
							$image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize(69, 87);
						   } else {
							$image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(69, 87);
						   }
						   ?>
						   <img src="<?php echo $image ?>" width="69" height="87" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 	'small_image'), null, true) ?>" />
						   </span>   
							</a>
						</div>
					</div>
					<div class="box-tab">
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php endif; ?>
						<div class="price-box">
									<?php
									$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
									$price = $_product->getPrice();
									$specialprice = $_product->getFinalPrice();
									if($price != $specialprice){
									if($price != ''){
									echo '<p class="old-price"><span class="price-label">';
									echo $this->__('Regular Price'). ': </span>';
									echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
									}
									if($specialprice != '')
									{
									echo '<p class="special-price">
									<span class="price-label">Special Price</span>
									<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
									</p> ';
									} 
									}else {
									echo '<div class="price-boxs">
									<span class="regular-price">
									<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
									</span>    
									</div>';    
									}
									?>
								</div>
					</div>
				</li>
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			</ul>
			<?php endif ?>
			<?php endforeach ?>
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div> <!-- #container -->

<script type="text/javascript">
</script> 
